### ISSUE TITLE
[TRACKER] Migrate Virtaal wiki to docs

### ISSUE THREAD

**Issue by dwaynebailey** [translate/virtaal#2783]
Depends on:
- [x] #2784 Convert Virtaal wiki docs to rST in docs/
- [x] #2785 Enable Virtaal RTD and redirects
- [ ] #2786 Migrate Virtaal document translation

Migrate the translate.sf.net/wiki/virtaal/index to docs/
