### ISSUE TITLE
Windows installer should package all dependencies

### ISSUE THREAD

**Issue by friedelwolff** [translate/virtaal#747]
Depends on:
- [x] #697 Virtaal should have spell checking on Windows
- [x] #741 Our Windows installer should package all translations of dependencies
- [x] #941 Automatic language guessing for files where language is unkown
- [x] #1166 Ship xgoogle with Virtaal

This is a central point to track the dependencies of certain Virtaal features for the sake of the Windows installer. This necessarily implies optional features. A few that come to mind:
- psycopg2
- spell checking (see bug #697)
- libtranslate
- sqlite3 with fts3 compiled in (how do we swap out the built-in sqlite library?)

Anything else?
